### ISSUE TITLE
Add VST2 SDK Link to README

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Bridge#1]
Hi @AndrewBelt,

Because a casual Google hits "VST2 is discontinued" instead of a download link, it is appropriate to include a link to the appropriate SDK in the Bridge README.  Please?

Thanks!

**Comment by AndrewBelt** [comment]
I'd rather not, I'll leave it as an exercise to the reader.

**Comment by djpeterso23662** [comment]
Okay, @AndrewBelt I trust your judgement.  Thanks for your time!

**Comment by AndrewBelt** [comment]
Yeah, because if I did, people would come to me for issues about building/using/licensing the VST SDK itself. So I'm distancing myself from it as much as possible by forcing people to realize that it's Steinberg's property and responsibility.

**Comment by AndrewBelt** [comment]
Added SDK URLs in 299f1a5

**Comment by djpeterso23662** [comment]
Hi @AndrewBelt!  When I built Bridge I used VST2_SDK=path on the make command line, after reading the Makefile for guidance.  It took me a couple tries to get it pointed at the correct folder.  This might be helpful to include in the README documentation.

**Comment by AndrewBelt** [comment]
Yes, I suppose you could define your own VST2_SDK location.

Added link.
