### ISSUE TITLE
How do I send MIDI from Ableton to the Bridge module?

### ISSUE THREAD

**Issue by steveangstrom** [VCVRack/Bridge#2]
Apologies for the basic question but I can't figure out how to send MIDI from Ableton Live to the Bridge MIDI module

Audio is working fine, as per the manual: I inserted the Bridge VST on an Ableton track and setting the Rack Audio out to "Bridge", "Port1" audio from Rack is then audible through an Ableton Live channel.  
However I failed to send MIDI.
In Rack I added a MIDI-1, set it to "Bridge" "port 1", "all channels" ... and I simply can't figure out how to pass MIDI from Ableton to that module. 

What am I missing?
Live 10.0.1  VCV Rack 0.6
![vcv-bridge-0 6](https://user-images.githubusercontent.com/8482649/38156357-2961b806-3475-11e8-8db6-e792cef86de9.png)

**Comment by AndrewBelt** [comment]
https://vcvrack.com/manual/Core.html

>Currently VCV Bridge is only a VST/AU effect plugin (Mac and 32/64-bit Windows) for using Rack as a send/return on a DAW track. VSTi/AU instrument plugins, MIDI, and DAW clock transport are coming soon in a later Rack 0.6.* update.
