### ISSUE TITLE
Can't find AU SDK files

### ISSUE THREAD

**Issue by CJunit** [VCVRack/Bridge#8]
I put the CoreAudio SDK folder in the Bridge/AU folder, but when I try to "make dist" I get an error that: BridgeAU.cpp:2:10: fatal error: 'AUMIDIEffectBase.h' file not found
...but the file in there in the Other Bases folder where it should be. 

/Rack/Bridge/AU/CoreAudio/AudioUnits/AUPublic/OtherBases/AUMIDIEffectBase.h

Is that right? The makefile shows that it is looking for it in (AU_SDK), is there some way I can direct the process so that those files are available? So that (AU_SDK) = CoreAudio folder?

**Comment by AndrewBelt** [comment]
I honestly have no idea where to "officially" obtain the AU SDK anymore. Apple removes random pages/files from their website on a whim. The instructions say

>For the AU plugin, obtain AudioUnitExamplesAudioUnitEffectGeneratorInstrumentMIDIProcessorandOffline/ from Apple's Core Audio SDK, and place it in the au/ directory.

But I have no idea where I obtained the horribly named `AudioUnitExamplesAudioUnitEffectGeneratorInstrumentMIDIProcessorandOffline` archive.

**Comment by CJunit** [comment]
What I mean is that the SDK is in the AU folder, it is "make" that can't find them. The file that it has a fatal error about is right there in the directory. My guess is that the makefile's (AU_SDK) is a variable which I need to do something to have it correctly recognize the existing directory.

**Comment by AndrewBelt** [comment]
Oh, okay. How did you obtain the AU/CoreAudio SDK, so I can add those instructions to the README?

Yeah, you can just use `make AU_SDK=CoreAudio` assuming the file exists at `$(AU_SDK)/AUPublic/OtherBases/AUMIDIEffectBase.h`

**Comment by CJunit** [comment]
I have had it since forever, but it currently resides here:
https://download.developer.apple.com/Developer_Tools/audio_tools_for_xcode__february_2012/audio_tools_for_xcode.dmg
Thanks for the tip, I'll try that!

**Comment by CJunit** [comment]
"make AU_SDK=CoreAudio" still got me the error, so I re-checked the makefile and saw that everything starting with AUPublic needs to be in the AudioUnits directory. So: 
$(AU_SDK)/AUPublic/AUBase/AUBase.cpp
becomes:
$(AU_SDK)/AudioUnits/AUPublic/AUBase/AUBase.cpp
etc.
Now it seems to find the files. But the build still fails with an error:
CoreAudio/AudioUnits/AUPublic/OtherBases/AUMIDIEffectBase.cpp:154:18: error: member 'MIDIEvent' found in multiple base classes of different types
                result = This->MIDIEvent(inStatus, inData1, inData2, inOffsetSampleFrame);
but that will need to wait until tomorrow. Thanks for the help.

**Comment by AndrewBelt** [comment]
I edited my post after commenting
